<h1>概要<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#练习题1" data-toc-modified-id="练习题1-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>练习题1</a></span></li><li><span><a href="#练习题2" data-toc-modified-id="练习题2-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>练习题2</a></span></li><li><span><a href="#练习题3" data-toc-modified-id="练习题3-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>练习题3</a></span></li><li><span><a href="#练习题4" data-toc-modified-id="练习题4-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>练习题4</a></span></li><li><span><a href="#练习题5" data-toc-modified-id="练习题5-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>练习题5</a></span></li><li><span><a href="#练习题6" data-toc-modified-id="练习题6-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>练习题6</a></span></li><li><span><a href="#练习题7" data-toc-modified-id="练习题7-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>练习题7</a></span></li><li><span><a href="#练习题8" data-toc-modified-id="练习题8-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>练习题8</a></span></li><li><span><a href="#练习题9" data-toc-modified-id="练习题9-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>练习题9</a></span></li><li><span><a href="#练习题10" data-toc-modified-id="练习题10-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>练习题10</a></span></li></ul></div>

本笔记基于天池龙珠计划SQL训练营及菜鸟教程等，仅供学习使用。<br>
实例：    实例（缩进）

SQL训练营页面地址：https://tianchi.aliyun.com/specials/promotion/aicampsql <br>
天池龙珠计划训练营地址：https://tianchi.aliyun.com/specials/promotion/aicamps<br>

**下载相关创建表格和插入数据脚本**  
这里为了方便大家，数据脚本已经给大家准备好啦。  
点击下方链接直接下载  
创建数据表脚本：http://tianchi-media.oss-cn-beijing.aliyuncs.com/dragonball/SQL/create_table.sql  
插入数据脚本：http://tianchi-media.oss-cn-beijing.aliyuncs.com/dragonball/SQL/data.zip  

大家下载好脚本后，先在MySQL环境中运行create_table.sql脚本，创建数据表，然后解压下载好的data.zip，解压后目录如下：  
    
    8-10ccf_offline_stage1_train.sql
    6-winequality-white.sql
    5-8-10ccf_online_stage1_train.sql
    4-macro industry.sql
    3-ccf_offline_stage1_test_revised.sql
    2-winequality-red.sql
    1-9income statement.sql
    1-9company operating.sql
    1-7market data.sql
    
脚本文件名前面的序号表示用到该数据集的题目序号，例如1-7market data.sql表示第1题和第7题用到了该数据集。  
同样的，这里给大家的也是sql脚本，里面是插入数据的语句，大家只需打开后在MySQL环境中运行即可将数据导入到数据表中。

# 练习题1
数据来源：https://tianchi.aliyun.com/dataset/dataDetail?dataId=1074

请使用A股上市公司季度营收预测数据集《Income Statement.xls》和《Company Operating.xlsx》和《Market Data.xlsx》，以Market Data为主表，将三张表中的TICKER_SYMBOL为600383和600048的信息合并在一起。只需要显示以下字段。  

|表名	|字段名|
|----|-----|
|Income Statement	|TICKER_SYMBOL|
|Income Statement	|END_DATE|
|Income Statement	|T_REVENUE|
|Income Statement	|T_COGS|
|Income Statement	|N_INCOME|
|Market Data	|TICKER_SYMBOL|
|Market Data	|END_DATE_|
|Market Data	|CLOSE_PRICE|
|Company Operating	|TICKER_SYMBOL|
|Company Operating	|INDIC_NAME_EN|
|Company Operating	|END_DATE|
|Company Operating	|VALUE|

    SELECT MarketData.*,
           OperatingData.INDIC_NAME_EN,
           OperatingData.VALUE,
           IncomeStatement.N_INCOME,
           IncomeStatement.T_COGS,
           IncomeStatement.T_REVENUE
      FROM ( -- market data
             SELECT TICKER_SYMBOL, END_DATE, CLOSE_PRICE
               FROM `market data`
              WHERE TICKER_SYMBOL IN('600383', '600048')) AS MarketData
      LEFT JOIN ( -- operating data
                  SELECT TICKER_SYMBOL, INDIC_NAME_EN, END_DATE, VALUE
                    FROM `company operating`
                   WHERE TICKER_SYMBOL IN('600383', '600048')) AS OperatingData 
        ON MarketData.TICKER_SYMBOL = OperatingData.TICKER_SYMBOL
       AND MarketData.END_DATE = OperatingData.END_DATE
      LEFT JOIN ( -- income statement
                  SELECT DISTINCT TICKER_SYMBOL, END_DATE, T_REVENUE, T_COGS, N_INCOME
                    FROM `income statement`
                   WHERE TICKER_SYMBOL IN('600383', '600048')) AS IncomeStatement 
        ON MarketData.TICKER_SYMBOL = IncomeStatement.TICKER_SYMBOL
       AND MarketData.END_DATE = IncomeStatement.END_DATE
     ORDER BY MarketData.TICKER_SYMBOL, MarketData.END_DATE;

# 练习题2
数据来源：https://tianchi.aliyun.com/dataset/dataDetail?dataId=44

请使用 Wine Quality Data 数据集《winequality-red.csv》，找出 pH=3.03的所有红葡萄酒，然后，对其 citric acid 进行中式排名（相同排名的下一个名次应该是下一个连续的整数值。换句话说，名次之间不应该有“间隔”）

    SELECT pH,
           `citric acid`,
           DENSE_RANK() OVER (ORDER BY `citric acid`) AS 'citric acid rank'
      FROM `winequality-red`
     WHERE pH = '3.03';

# 练习题3
数据来源：https://tianchi.aliyun.com/competition/entrance/231593/information

使用Coupon Usage Data for O2O中的数据集《ccf_offline_stage1_test_revised.csv》，试分别找出在2016年7月期间，发放优惠券总金额最多和发放优惠券张数最多的商家。

这里只考虑满减的金额，不考虑打几折的优惠券。

    -- 2016年7月期间，商家发放优惠券金额及数量表 
     WITH discount_table AS
    ( 
        SELECT Merchant_id,
               SUM(MID(Discount_rate, INSTR(Discount_rate, ':') + 1)) AS Amount,
               COUNT(Coupon_id) AS Quantity
          FROM ccf_offline_stage1_test_revised
         WHERE Date_received BETWEEN '2016-07-01' AND '2016-07-31'
           AND INSTR(Discount_rate, '.') = 0
         GROUP BY Merchant_id
    )
    -- 发放优惠券总⾦额最多的商家
    SELECT Merchant_id,
           Amount,
           Quantity
      FROM discount_table
     WHERE Amount = (SELECT MAX(Amount) FROM discount_table)
    UNION
    -- 发放优惠券张数最多的商家
    SELECT Merchant_id,
           Amount,
           Quantity
      FROM discount_table
     WHERE Quantity = (SELECT MAX(Quantity) FROM discount_table);

# 练习题4
数据来源：https://tianchi.aliyun.com/dataset/dataDetail?dataId=1074

请使用A股上市公司季度营收预测中的数据集《Macro&Industry.xlsx》中的sheet-INDIC_DATA，请计算全社会用电量:第一产业:当月值在2015年用电最高峰是发生在哪月？并且相比去年同期增长/减少了多少个百分比？

    -- 2015年第一产业用电量
    WITH pi_c2015 AS 
    (
        SELECT name_cn,
               PERIOD_DATE,
               DATA_VALUE 
          FROM `macro industry` 
         WHERE name_cn = 'Total Electricity Consumption: Primary Industry'
           AND YEAR(PERIOD_DATE) = 2015
    ), 
    -- 2014年第一产业用电量
    pi_c2014 AS 
    (
        SELECT name_cn,
               PERIOD_DATE,
               DATA_VALUE 
          FROM `macro industry` 
         WHERE name_cn = 'Total Electricity Consumption: Primary Industry'
           AND YEAR(PERIOD_DATE) = 2014
    ) 
    SELECT c2015.name_cn,
           MONTH(c2015.PERIOD_DATE) AS '2015年用电高峰月',
           c2015.DATA_VALUE AS '2015年用电高峰月用电量',
           c2014.DATA_VALUE AS '去年同期用电量',
           ROUND((c2015.DATA_VALUE - c2014.DATA_VALUE) * 100 / c2014.DATA_VALUE, 2) 
                            AS '同比增长百分比'
      FROM pi_c2015 AS c2015
     INNER JOIN pi_c2014 AS c2014 ON MONTH(c2014.PERIOD_DATE) = MONTH(c2015.PERIOD_DATE)
     WHERE c2015.DATA_VALUE = (SELECT MAX(DATA_VALUE) 
                                 FROM pi_c2015);

# 练习题5
数据来源：https://tianchi.aliyun.com/competition/entrance/231593/information

使用Coupon Usage Data for O2O中的数据集《ccf_online_stage1_train.csv》，试统计在2016年6月期间，线上总体优惠券弃用率为多少？并找出优惠券弃用率最高的商家。

弃用率 = 被领券但未使用的优惠券张数 / 总的被领取优惠券张数

    -- 2016年6⽉期间，线上总体优惠券弃⽤率为多少？
    SELECT (COUNT(Coupon_id) - COUNT(Date)) / COUNT(Coupon_id) AS '总体优惠券弃用率'
      FROM ccf_online_stage1_train 
     WHERE Date_received BETWEEN '2016-06-01' AND '2016-06-30'
       AND Coupon_id IS NOT NULL;

    -- 2016年6⽉期间，优惠券弃⽤率最⾼的商家？
    WITH unused_coupon AS 
    ( 
       SELECT Merchant_id,
              COUNT(Coupon_id) AS quantity,
              ROUND((COUNT(Coupon_id) - COUNT(Date)) / COUNT(Coupon_id), 2) AS rate
         FROM ccf_online_stage1_train 
        WHERE Date_received BETWEEN '2016-06-01' AND '2016-06-30'
          AND Coupon_id IS NOT NULL
        GROUP BY Merchant_id 
    ) 
    SELECT Merchant_id, 
           quantity AS '优惠券发放量',
           rate AS '优惠券弃用率'
      FROM unused_coupon
     WHERE rate = (SELECT MAX(rate) FROM unused_coupon)
     ORDER BY quantity DESC;

# 练习题6
数据来源：https://tianchi.aliyun.com/dataset/dataDetail?dataId=44

请使用 Wine Quality Data 数据集《winequality-white.csv》，找出 pH=3.63的所有白葡萄酒，然后，对其 residual sugar 量进行英式排名（非连续的排名）

    SELECT pH,
           `residual sugar`,
           RANK() OVER (ORDER BY `residual sugar`)  AS 'residual sugar rank'
      FROM `winequality-white`
     WHERE pH= 3.63;

# 练习题7
数据来源：https://tianchi.aliyun.com/dataset/dataDetail?dataId=1074

请使用A股上市公司季度营收预测中的数据集《Market Data.xlsx》中的sheet-DATA，

计算截止到2018年底，市值最大的三个行业是哪些？以及这三个行业里市值最大的三个公司是哪些？（每个行业找出前三大的公司，即一共要找出9个）

    -- 截止到2018年底，市值最大的三个行业 
    WITH top3_industry AS 
    (
        SELECT TYPE_NAME_CN,
               SUM(MARKET_VALUE) AS INDUSTRY_MARKET_VALUE
          FROM `market data`
         WHERE YEAR(END_DATE) = '2018-12-31'
         GROUP BY TYPE_NAME_CN
         ORDER BY INDUSTRY_MARKET_VALUE DESC
         LIMIT 3
    ),
    -- 2018年，各公司市值
    company_market_value AS 
    ( 
        SELECT TICKER_SYMBOL,
               TYPE_NAME_CN,
               MARKET_VALUE,
               RANK() OVER (PARTITION BY TYPE_NAME_CN ORDER BY MARKET_VALUE DESC) AS 'rank'
          FROM `market data`
         WHERE YEAR(END_DATE) = '2018-12-31'
    )
    SELECT i.*,
           c.TICKER_SYMBOL,
           c.MARKET_VALUE,
           c.rank
      FROM top3_industry AS i
      LEFT JOIN company_market_value AS c ON i.TYPE_NAME_CN = c.TYPE_NAME_CN
     WHERE c.`rank` <= 3
     ORDER BY INDUSTRY_MARKET_VALUE DESC, MARKET_VALUE DESC;

# 练习题8
数据来源：https://tianchi.aliyun.com/competition/entrance/231593/information

使用Coupon Usage Data for O2O中的数据集《ccf_online_stage1_train.csv》和《ccf_offline_stage1_train.csv》，试找出在2016年6月期间，线上线下累计优惠券使用次数最多的顾客。

    -- 统计2016年6月期间用户使用优惠券次数（线上/线下）
     WITH union_table AS
    (
        SELECT User_id,
               COUNT(Date) AS times
           FROM ccf_online_stage1_train AS c1
          WHERE c1.Coupon_id IS NOT NULL 
           AND c1.Date BETWEEN '2016-06-01' AND '2016-06-30'
         GROUP BY User_id
         UNION ALL
        SELECT User_id,
               COUNT(Date) AS times
           FROM ccf_offline_stage1_train AS c2
          WHERE c2.Coupon_id IS NOT NULL 
           AND c2.Date BETWEEN '2016-06-01' AND '2016-06-30'
         GROUP BY User_id
    ),
    -- 汇总用户及其使用优惠券次数
    user_times AS
    (
       SELECT User_id,
              SUM(times) AS times
         FROM union_table
        GROUP BY User_id
    )
    SELECT User_id,
           times AS `优惠券使用次数`
      FROM user_times
     WHERE times = (SELECT MAX(times) FROM user_times);

# 练习题9
数据来源：https://tianchi.aliyun.com/dataset/dataDetail?dataId=1074

请使用A股上市公司季度营收预测数据集《Income Statement.xls》中的sheet-General Business和《Company Operating.xlsx》中的sheet-EN。

找出在数据集所有年份中，按季度统计，白云机场旅客吞吐量最高的那一季度对应的净利润是多少？（注意，是单季度对应的净利润，非累计净利润。）

    -- 白云机场各季度旅客吞吐量
    WITH Baiyun_season_pt AS
    (
        SELECT INDIC_NAME_EN,
               TICKER_SYMBOL,
               YEAR(END_DATE) AS 'year',
               QUARTER(END_DATE) AS season,
               SUM(VALUE) AS ptvalue
          FROM `company operating`
         WHERE INDIC_NAME_EN = 'Baiyun Airport:Passenger throughput'
         GROUP BY TICKER_SYMBOL, year, season
    ),
    -- 公司各季度净利润
    company_season_income AS
    (
        SELECT TICKER_SYMBOL,
               YEAR(END_DATE) AS 'year',
               QUARTER(END_DATE) AS season,
               SUM(N_INCOME) AS income
          FROM `income statement`
         GROUP BY TICKER_SYMBOL, year, season
    )
    SELECT pt.INDIC_NAME_EN,
           pt.year,
           pt.season,
           pt.ptvalue AS 'passenger throughput',
           i.income
      FROM Baiyun_season_pt AS pt
     INNER JOIN company_season_income AS i
        ON pt.TICKER_SYMBOL = i.TICKER_SYMBOL
       AND pt.year = i.year
       AND pt.season = i.season
     WHERE pt.ptvalue = (SELECT MAX(ptvalue) FROM Baiyun_season_pt);

# 练习题10
数据来源：https://tianchi.aliyun.com/competition/entrance/231593/information

使用Coupon Usage Data for O2O中的数据集《ccf_online_stage1_train.csv》和《ccf_offline_stage1_train.csv》，试找出在2016年6月期间，线上线下累计被使用优惠券满减最多的前3名商家。

比如商家A，消费者A在其中使用了一张200减50的，消费者B使用了一张30减1的，那么商家A累计被使用优惠券满减51元。

    -- 2016年6月期间，商家累计满减（线上/线下）
    WITH merchant_coupon AS
    (
        SELECT Merchant_id,
               SUM(MID(Discount_rate, INSTR(Discount_rate, ':') + 1)) AS Amount
          FROM ccf_online_stage1_train
         WHERE Coupon_id IS NOT NULL 
           AND Date BETWEEN '2016-06-01' AND '2016-06-30'
           AND INSTR(Discount_rate, '.') = 0
         GROUP BY Merchant_id
        UNION ALL
        SELECT Merchant_id,
               SUM(MID(Discount_rate, INSTR(Discount_rate, ':') + 1)) AS Amount
          FROM ccf_offline_stage1_train
         WHERE Coupon_id IS NOT NULL 
           AND INSTR(Date, '201606') = 1
           AND INSTR(Discount_rate, '.') = 0
         GROUP BY Merchant_id
    )
    SELECT Merchant_id,
           SUM(Amount) AS Discount_amount
      FROM merchant_coupon
     GROUP BY Merchant_id
     ORDER BY Discount_amount DESC
     LIMIT 3;